- README.md
> PR made from bash

- mlflow/src/tracking_server/run_management.js
Added createRun, deleteRun, restoreRun, getRun, updateRun methods to the Run module. 
Tested with Postman and example code locally.
> feat: Added createRun, deleteRun, restoreRun, getRun, updateRun methods to the Run module

- mlflow/src/tracking_server/experiment_management.js
- mlflow/src/tracking_server/tempCodeRunnerFile.js
https://trello.com/c/bHTTqZMo/5-module-experiment-management
removed use of try/catch blocks.  improvements to function returns (more specific)
n/a
> feat: removed use of try/catch blocks.  improvements to function returns (more specific)

- mlflow/package-lock.json
- mlflow/src/tracking_server/run_management.js
- mlflow/src/tracking_server/testing.js
Added logMetric, logBatch, logModel, logInputs to the run management module.
> feat: Added logMetric, logBatch, logModel, logInputs to the run management module and a testing file for reference

- mlflow/src/model_registry/model_version_management.js
> build: model version mgmt

- mlflow/docs/typescript-code-standards.md
- mlflow/src/model-registry/ModelRegistryClient.ts
- mlflow/tests/ModelRegistryClientTest.ts
- mlflow/tsconfig.json
> feat: Add path config, refactor import path, add code standards file

- mlflow/docs/typescript-code-standards.md
> fix: code standards

- .github/workflows/mlflow-js.yaml
- mlflow/.gitignore
- mlflow/eslint.config.mjs
Added rules to eslint.config.mjs to turn off errors on 'no-explicit-any' and 'no-console'.
Added a yaml to github/workflows to branch stephany/github-actions-3 for testing.
> fix&feat: Add rules to eslint.config.mjs, setup github actions for branch stephany/github-actions-3

- mlflow/package-lock.json
- mlflow/package.json
- mlflow/tests/ExperimentClientTestFile.ts
- mlflow/tests/ExperimentManagerTestFile.ts
- mlflow/tsconfig.json
- mlflow/typedoc.json
> feat: Removed Typedoc and Eslint fully passing now

- mlflow-site/src/app/components/Button.tsx
- mlflow-site/src/app/globals.css
- mlflow/src/workflows/ExperimentManager.ts
- mlflow/src/workflows/ModelManager.ts
- mlflow/src/workflows/RunManager.ts
- mlflow/tests/ModelManagerTest.ts
- mlflow/tests/ModelRegistryClientTest.ts
- mlflow/tests/ModelVersionClientTest.ts
- mlflow/tests/RunClientTest.ts
- mlflow/tests/RunManagerTestFile.ts
- mlflow/tsconfig.json
> fix: Fixed npm run build Errors

- mlflow/docs/tech-design-doc.md
> feat: Update tech-design-doc.md

- mlflow-site/package.json
- mlflow-site/src/app/components/Demo.tsx
- mlflow-site/src/app/components/DemoCard.tsx
https://trello.com/c/uTXMYBBL/74-featurestsx-and-demotsx
Added embedded Vimeo players to the DemoCard.tsx component to show demo videos
n/a
> feat: embedded Vimeo players in the DemoCard.tsx component of splash site

- mlflow/eslint.config.mjs
- mlflow/jest.config.ts
- mlflow/package-lock.json
- mlflow/package.json
- mlflow/src/utils/interface.ts
- mlflow/src/workflows/RunManager.ts
- mlflow/tests/RunClient.test.ts
- mlflow/tsconfig.json
> feat: Jest example with createRun

- mlflow/jest.config.ts
- mlflow/package.json
- mlflow/tsconfig.json
- mlflow/tsconfig.test.json
> feature: change jest test setting, clean up package.json and tsconfig.json, add tsconfig.test.json

- mlflow-site/src/app/components/Demo.tsx
https://trello.com/c/IHkl6eCz/45-splash-site-3-demo-videos
added Vimeo link for 'Managing Experiments in MLflow.js' to Demo.tsx for splash site
n/a
> feat: added Vimeo link for 'Managing Experiments in MLflow.js' to Demo.tsx for splash site

- README.md
> Update README.md - usage example code

- mlflow/examples/NeuralNetworkHyperparameterTuning.js
> feat: add NN multi run example

- mlflow-site/src/app/components/Demo.tsx
- mlflow-site/src/app/components/Features.tsx
- mlflow-site/src/app/documentation/page.tsx
- mlflow-site/src/app/globals.css
n/a
Minor styling tweaks: fonts, spacing, etc
n/a
> feat: styling changex

- mlflow-site/src/app/components/Demo.tsx
- mlflow-site/src/app/components/Features.tsx
- mlflow-site/src/app/documentation/page.tsx
https://trello.com/c/pj9XhsYD/66-write-splash-site-copy
splash site text
n/a
> feat: added splash site text

- README.md
- mlflow-site/src/app/components/Button.tsx
> fix: Fixed small typos in README.md

- .github/README.md
- mlflow/README.md
- mlflow/package.json
> feat: revise Readme

- mlflow-site/src/app/components/Demo.tsx
- mlflow-site/src/app/components/Features.tsx
- mlflow-site/src/app/components/Headline.tsx
- mlflow-site/src/app/documentation/page.tsx
> feature: revise some site descriptions

- mlflow-site/src/app/components/DemoCard.tsx
n/a
fixed splash site type error related to anchor tag (see DemoCard blurb)
n/a
> fixed type error related to DemoCardBlurb
